// Agregar estas entradas al array PROGRAMS de seed/_data-academicprogram.js
  { institutionCode: 'UPU-MAIN', code: "UPU-ICIV", name: "Ingenieria Civil", degree: "Bachelor", modality: "InPerson", nominalDuration: 10 },
  { institutionCode: 'UPU-MAIN', code: "UPU-IINF", name: "Ingenieria en Informatica", degree: "Bachelor", modality: "Online", nominalDuration: 8 },
  { institutionCode: 'UPU-MAIN', code: "UPU-IIND", name: "Ingenieria Industrial", degree: "Bachelor", modality: "Hybrid", nominalDuration: 10 },
  { institutionCode: 'UPU-MAIN', code: "UPU-IELE", name: "Ingenieria Electrica", degree: "Bachelor", modality: "InPerson", nominalDuration: 10 },
  { institutionCode: 'UPU-MAIN', code: "UPU-LMAT", name: "Licenciatura en Matematicas", degree: "Bachelor", modality: "InPerson", nominalDuration: 8 },
  { institutionCode: 'UPU-MAIN', code: "UPU-LFIS", name: "Licenciatura en Fisica", degree: "Bachelor", modality: "InPerson", nominalDuration: 8 },
  { institutionCode: 'UPU-MAIN', code: "UPU-LQUI", name: "Licenciatura en Quimica", degree: "Bachelor", modality: "Hybrid", nominalDuration: 8 },
  { institutionCode: 'UPU-MAIN', code: "UPU-LBIO", name: "Licenciatura en Biologia", degree: "Bachelor", modality: "InPerson", nominalDuration: 8 },
  { institutionCode: 'UPU-MAIN', code: "UPU-MCDA", name: "Magister en Ciencia de Datos", degree: "Master", modality: "Online", nominalDuration: 4 },
  { institutionCode: 'UPU-MAIN', code: "UPU-MMAT", name: "Magister en Matematica Aplicada", degree: "Master", modality: "Hybrid", nominalDuration: 4 },
  { institutionCode: 'UPU-MAIN', code: "UPU-MISW", name: "Magister en Ingenieria de Software", degree: "Master", modality: "Online", nominalDuration: 4 },
  { institutionCode: 'UPU-MAIN', code: "UPU-MGAM", name: "Magister en Gestion Ambiental", degree: "Master", modality: "Hybrid", nominalDuration: 4 },
  { institutionCode: 'UPU-MAIN', code: "UPU-DCIE", name: "Doctorado en Ciencias", degree: "Doctorate", modality: "InPerson", nominalDuration: 8 },
  { institutionCode: 'UPU-MAIN', code: "UPU-DING", name: "Doctorado en Ingenieria", degree: "Doctorate", modality: "InPerson", nominalDuration: 8 },
  { institutionCode: 'UPU-MAIN', code: "UPU-DFIS", name: "Doctorado en Fisica", degree: "Doctorate", modality: "InPerson", nominalDuration: 8 },
  { institutionCode: 'UPU-MAIN', code: "UPU-TRED", name: "Tecnico en Redes y Telecomunicaciones", degree: "Technical", modality: "InPerson", nominalDuration: 5 },
  { institutionCode: 'UPU-MAIN', code: "UPU-TWEB", name: "Tecnico en Desarrollo Web", degree: "Technical", modality: "Online", nominalDuration: 5 },
  { institutionCode: 'UPU-MAIN', code: "UPU-TQUI", name: "Tecnico en Analisis Quimico", degree: "Technical", modality: "InPerson", nominalDuration: 5 },
  { institutionCode: 'UPU-MAIN', code: "UPU-TENR", name: "Tecnico en Energias Renovables", degree: "Technical", modality: "Hybrid", nominalDuration: 5 },
  { institutionCode: 'UPU-MAIN', code: "UPU-TPRG", name: "Tecnico en Programacion", degree: "Technical", modality: "Online", nominalDuration: 4 },
